// frontend/src/components/boxEditors/Basics.vue
<script setup>
import { inject } from "vue";
import Select from "primevue/select";
import InputNumber from "primevue/inputnumber";
import IftaLabel from "primevue/iftalabel";

const mon = defineModel();
const PF = inject("PF");
const pokemon = inject("pokemon");
const abilities = inject("abilities");
const items = inject("items");
const growthRates = inject("growthRates");

const getAbilities = () => {
  let species = pokemon.value[PF].find(
    (species) => species["Name"] === mon.value["Species"]
  );
  let form = species["Forms"].find(
    (form) => form["Name"] === mon.value["Form"]
  );
  return form["Abilities"];
};

const getGrowthRate = () => {
  let species = pokemon.value[PF].find(
    (species) => species["Name"] === mon.value["Species"]
  );
  let form = species["Forms"].find(
    (form) => form["Name"] === mon.value["Form"]
  );
  return form["Growth Rate"].slice(6);
};

const getExpForLevel = (level) => {
  // Formula: [1]/[2]*n**3 + [3]*n**2 + [4]*n - [5]
  const growthCFs = growthRates.value[getGrowthRate()];
  return Math.ceil(
    (growthCFs[0] / growthCFs[1]) * level ** 3 +
    growthCFs[2] * level ** 2 +
    growthCFs[3] * level -
    growthCFs[4]
  );
};
</script>

<template>
  <div>
    <span class="text-lg font-semibold">Held Item</span> <br />
    <Select
      class="mt-3 mb-3"
      v-model="mon['Held Item']"
      :options="[...items[PF].map((item) => item['Name']), 'None']"
      filter
      fluid
    />
    <p>
      {{
        items[PF].find((item) => item["Name"] === mon["Held Item"])?.[
          "Description"
        ] || "This Pokémon has no held item."
      }}
    </p>
    <br />
    <span class="text-lg font-semibold">Ability</span> <br />
    <Select
      class="mt-3 mb-3"
      v-model="mon['Ability']"
      :options="getAbilities()"
      fluid
    />
    <p>
      {{
        abilities[PF].find((ability) => ability["Name"] === mon["Ability"])[
          "Description"
        ]
      }}
    </p>
    <br />
    <span class="text-lg font-semibold">Level / Experience</span>
    <IftaLabel class="mt-3 mb-3">
      <InputNumber
        id="level"
        v-model="mon['Level']"
        :min="0"
        :max="100"
        fluid
      />
      <label for="level">Level</label>
    </IftaLabel>
    <p>{{ getExpForLevel(1) - getExpForLevel(0) }}</p>
  </div>
</template>

// src/lib/components/mon/basics.svelte
<script lang="ts">
	import type { Form, Species } from '$extractors/types';
	import type { BoxMon, PartyMon } from '$parsers/types';
	import NumberInput from '$ui/number-input.svelte';
	import TextInput from '$ui/text-input.svelte';
	import ItemIcon from '$ui/item-icon.svelte';
	import { Heading, P } from 'flowbite-svelte';
	import pokemon from '$data/pokemon.json';
	import items from '$data/items.json';
	import DropdownSelect from '$ui/dropdown-select.svelte';
	import Combobox from '$ui/combobox.svelte';

	interface BasicsProps {
		mon: PartyMon | BoxMon;
		species: Species;
		form: Form;
		PF: 'polished' | 'faithful';
	}

	let { mon = $bindable(), species, form, PF }: BasicsProps = $props();

	function resetMon(): void {
		mon.form = species.forms.find((f) => f.index === 1)!.name;
		resetForm();
	}
	function resetForm(): void {
		mon.ability = form.abilities[0];
		mon.gender = form.hasGender ? mon.gender : 'Genderless';
		setExpForLvl();
	}

	function setExpForLvl(): void {
		mon.exp = Math.max(
			Math.floor((form.growthCFs[0] / form.growthCFs[1]) * mon.level ** 3) +
				form.growthCFs[2] * mon.level ** 2 +
				form.growthCFs[3] * mon.level -
				form.growthCFs[4],
			0
		);
	}
</script>

<Heading tag="h5">Nickname</Heading>
<TextInput bind:value={mon.nickname} maxLength={10} class="my-5" />

<Heading tag="h5">Species & Form</Heading>
<div class="flex gap-3 my-5">
	<Combobox
		options={pokemon[PF].map((p) => p.name).filter((p) => !'?000?Egg?256?'.includes(p))}
		bind:value={mon.species}
		onchange={resetMon}
	/>
	<DropdownSelect
		options={species.forms.map((f) => f.name)}
		bind:value={mon.form}
		onchange={resetForm}
	/>
</div>

<Heading tag="h5" class="mb-5">Held Item</Heading>
{#if 'currentHP' in mon}
	<Combobox
		options={['None'].concat(items[PF].slice(1).map((item) => item.name))}
		bind:value={mon.heldItem}
	/>
{:else}
	<Combobox
		options={['None']
			.concat(items[PF].map((item) => item.name))
			.filter((name) => !name.includes('Mail'))}
		bind:value={mon.heldItem}
	/>
{/if}
<div class="flex items-center mt-5 gap-3">
	<ItemIcon heldItem={mon.heldItem} {PF} />
	{#if mon.heldItem === 'None'}
		<P italic>This Pokemon has no held item.</P>
	{:else}
		<P italic>{items[PF].find((i) => i.name === mon.heldItem)!.description}</P>
	{/if}
</div>

<Heading tag="h5" class="mt-5 mb-[-10px]">Level</Heading>
<NumberInput bind:value={mon.level} min={1} max={100} onchange={setExpForLvl} />
