// frontend/src/components/boxEditors/Moveset.vue
<script setup>
import { inject, ref, onBeforeMount } from "vue";
import Select from "primevue/select";

const mon = defineModel();
const moves = inject("moves");
const PF = inject("PF");

const getMove = (moveName) => {
  //If no move
  if (moveName === "---") {
    return {
      Type: "-",
      "Base Power": "-",
      Accuracy: "-",
      "Power Points": "-",
      "Effect Chance": "-",
      "Damage Category": "-",
    };
  }
  return moves.value[PF].find((move) => moveName === move["Name"]);
};
</script>

<template>
  <div v-if="moves" class="flex flex-col gap-3">
    <div v-for="(move, index) in mon['Moves']">
      <Select
        class="w-full"
        v-model="mon['Moves'][index]"
        :options="[...moves[PF].map((move) => move['Name']), '---']"
        filter
      />
      <div class="grid grid-cols-2 gap-1 mt-3">
        <div>
          Type:
          {{
            getMove(move)["Type"].at(0).toUpperCase() +
            getMove(move)["Type"].slice(1)
          }}
        </div>
        <div>Base Power: {{ getMove(move)["Base Power"] }}</div>
        <div>
          Category:
          {{
            getMove(move)["Damage Category"].at(0).toUpperCase() +
            getMove(move)["Damage Category"].slice(1)
          }}
        </div>
        <div>Accuracy: {{ getMove(move)["Accuracy"] }}%</div>
        <div>Power Points: {{ getMove(move)["Power Points"] }}</div>
        <div>Effect Chance: {{ getMove(move)["Effect Chance"] }}%</div>
      </div>
    </div>
  </div>
</template>

// src/lib/components/monEditors/Moveset.svelte
<script>
	import { P } from 'flowbite-svelte';
	import { DropdownSearch } from '$components/UI';
	import { moves } from '$data';
	let { mon = $bindable(), PF } = $props();
	let MOVES = $derived.by(() => {
		const result = [];
		for (let move of mon.moves) {
			if (move === 'Empty') {
				result.push('Empty');
				continue;
			}
			result.push(moves[PF].find((MOVE) => MOVE.name === move));
		}
		return result;
	});
</script>

<div class="flex flex-col gap-3">
	{#each mon.moves as move, i}
		<div>
			<DropdownSearch
				bind:value={mon.moves[i]}
				options={['Empty', ...moves[PF].map((move) => move.name)]}
			/>
			{#if move === 'Empty'}
				<P class="mt-3">This moveslot is empty.</P>
			{:else}
				<div class="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-2 md:grid-cols-3">
					<P>Type: {MOVES[i].type.at(0).toUpperCase() + MOVES[i].type.slice(1)}</P>
					<P>Base Power: {MOVES[i].basePower}</P>
					<P>Accuracy: {MOVES[i].accuracy}</P>
					<P>Category: {MOVES[i].category.at(0).toUpperCase() + MOVES[i].category.slice(1)}</P>
					<P>Power Points: {MOVES[i].pp}</P>
					<P>Effect Chance: {MOVES[i].effectChance}</P>
				</div>
			{/if}
		</div>
	{/each}
</div>
