// src/lib/components/monEditors/Basics.svelte
<script>
	import { Heading } from 'flowbite-svelte';
	import items from '$data/items.json';
	import pokemon from '$data/pokemon.json';
	import growthRates from '$data/growthRates.json';
	import { DropdownSearch, NumberInput, RadioSelect } from '$components/UI';
	let { mon = $bindable(), PF } = $props();

	const setExpForLvl = () => {
		//Formula: [1]/[2]*n**3 + [3]*n**2 + [4]*n - [5]
		const growthCFs = growthRates[getGrowthRate()];
		mon.exp = Math.ceil(
			(growthCFs[0] / growthCFs[1]) * mon.level ** 3 +
				growthCFs[2] * mon.level ** 2 +
				growthCFs[3] * mon.level -
				growthCFs[4]
		);
	};
	const getGrowthRate = () => {
		return pokemon[PF].find((pokemon) => pokemon.name === mon.species)
			.forms.find((form) => form.name === mon.form)
			.growthRate.slice(6);
	};

	const resetSpecies = () => {
		const species = pokemon[PF].find((pokemon) => pokemon.name === mon.species);
		const form = species.forms[0];
		mon.form = form.name;
		mon.ability = form.abilities[0];
		setExpForLvl();
	};

	const resetForm = () => {
		const form = pokemon[PF].find((pokemon) => pokemon.name === mon.species).forms.find(
			(form) => form.name === mon.form
		);
		mon.ability = form.abilities[0];
		setExpForLvl();
	};
</script>

<Heading tag="h6" class="mb-3">Species & Form</Heading>
<div class="flex gap-3">
	<DropdownSearch
		class="flex-1"
		bind:value={mon.species}
		options={pokemon[PF].map((pokemon) => pokemon.name)}
		onchange={resetSpecies}
	/>
	<DropdownSearch
		class="flex-1"
		bind:value={mon.form}
		options={pokemon[PF].find((pokemon) => pokemon.name === mon.species).forms.map(
			(form) => form.name
		)}
		onchange={resetForm}
	/>
</div>

<Heading tag="h6" class="mt-3 mb-3">Held Item</Heading>
<DropdownSearch
	bind:value={mon.heldItem}
	options={['None', ...items[PF].map((item) => item.name)]}
/>

<Heading tag="h6" class="mt-3 mb-3">Ability</Heading>
<RadioSelect
	bind:value={mon.ability}
	options={pokemon[PF].find((pokemon) => pokemon.name === mon.species).forms.find(
		(form) => form.name === mon.form
	).abilities}
/>

<Heading tag="h6" class="mt-3 mb-3">Level</Heading>
<NumberInput bind:value={mon.level} min={1} max={100} onchange={() => setExpForLvl()} />

// frontend/src/components/boxEditors/Basics.vue
<script setup>
import { inject } from "vue";
import Select from "primevue/select";
import InputNumber from "primevue/inputnumber";
import IftaLabel from "primevue/iftalabel";

const mon = defineModel();
const PF = inject("PF");
const pokemon = inject("pokemon");
const abilities = inject("abilities");
const items = inject("items");
const growthRates = inject("growthRates");

const getAbilities = () => {
  let species = pokemon.value[PF].find(
    (species) => species["Name"] === mon.value["Species"]
  );
  let form = species["Forms"].find(
    (form) => form["Name"] === mon.value["Form"]
  );
  return form["Abilities"];
};

const getGrowthRate = () => {
  let species = pokemon.value[PF].find(
    (species) => species["Name"] === mon.value["Species"]
  );
  let form = species["Forms"].find(
    (form) => form["Name"] === mon.value["Form"]
  );
  return form["Growth Rate"].slice(6);
};

const getExpForLevel = (level) => {
  // Formula: [1]/[2]*n**3 + [3]*n**2 + [4]*n - [5]
  const growthCFs = growthRates.value[getGrowthRate()];
  return Math.ceil(
    (growthCFs[0] / growthCFs[1]) * level ** 3 +
    growthCFs[2] * level ** 2 +
    growthCFs[3] * level -
    growthCFs[4]
  );
};
</script>

<template>
  <div>
    <span class="text-lg font-semibold">Held Item</span> <br />
    <Select
      class="mt-3 mb-3"
      v-model="mon['Held Item']"
      :options="[...items[PF].map((item) => item['Name']), 'None']"
      filter
      fluid
    />
    <p>
      {{
        items[PF].find((item) => item["Name"] === mon["Held Item"])?.[
          "Description"
        ] || "This Pokémon has no held item."
      }}
    </p>
    <br />
    <span class="text-lg font-semibold">Ability</span> <br />
    <Select
      class="mt-3 mb-3"
      v-model="mon['Ability']"
      :options="getAbilities()"
      fluid
    />
    <p>
      {{
        abilities[PF].find((ability) => ability["Name"] === mon["Ability"])[
          "Description"
        ]
      }}
    </p>
    <br />
    <span class="text-lg font-semibold">Level / Experience</span>
    <IftaLabel class="mt-3 mb-3">
      <InputNumber
        id="level"
        v-model="mon['Level']"
        :min="0"
        :max="100"
        fluid
      />
      <label for="level">Level</label>
    </IftaLabel>
    <p>{{ getExpForLevel(1) - getExpForLevel(0) }}</p>
  </div>
</template>
