// frontend/src/components/MonEditor.vue
<script setup>
import Accordion from "primevue/accordion";
import AccordionPanel from "primevue/accordionpanel";
import AccordionHeader from "primevue/accordionheader";
import AccordionContent from "primevue/accordioncontent";
import DVEVNature from "./boxEditors/DVEVNature.vue";
import Moveset from "./boxEditors/Moveset.vue";
import Basics from "./boxEditors/Basics.vue";
import Misc from "./boxEditors/Misc.vue";

const mon = defineModel();
</script>

<template>
  <Accordion class="m-0">
    <AccordionPanel value="basic">
      <AccordionHeader>Basics</AccordionHeader>
      <AccordionContent>
        <Basics v-model="mon" />
      </AccordionContent>
    </AccordionPanel>
    <AccordionPanel value="stats">
      <AccordionHeader>DVs, EVs & Natures</AccordionHeader>
      <AccordionContent>
        <DVEVNature v-model="mon" />
      </AccordionContent>
    </AccordionPanel>
    <AccordionPanel value="moves">
      <AccordionHeader>Moveset</AccordionHeader>
      <AccordionContent>
        <Moveset v-model="mon" />
      </AccordionContent>
    </AccordionPanel>
    <AccordionPanel value="misc">
      <AccordionHeader>Miscellaneous</AccordionHeader>
      <AccordionContent>
        <Misc v-model="mon" />
      </AccordionContent>
    </AccordionPanel>
  </Accordion>
</template>

// src/lib/components/MonEditor.svelte
<script>
	import { Heading, Accordion, AccordionItem } from 'flowbite-svelte';
	import DVEVNature from './monEditors/DVEVNature.svelte';
	import Misc from './monEditors/Misc.svelte';
	import Moveset from './monEditors/Moveset.svelte';
	import Basics from './monEditors/Basics.svelte';
	let { mon = $bindable(), PF } = $props();
</script>

<Heading tag="h3">Edit {mon.species}</Heading>

<Accordion class="mt-4">
	<AccordionItem open>
		{#snippet header()}Basics{/snippet}
		<Basics bind:mon {PF} />
	</AccordionItem>
	<AccordionItem>
		{#snippet header()}DVs, EVs & Nature{/snippet}
		<DVEVNature bind:mon />
	</AccordionItem>
	<AccordionItem>
		{#snippet header()}Moveset{/snippet}
		<Moveset bind:mon {PF} />
	</AccordionItem>
	<AccordionItem>
		{#snippet header()}Miscellaneous{/snippet}
		<Misc bind:mon {PF} />
	</AccordionItem>
</Accordion>
